baseURL = "https://jneo8.github.io"
languageCode = "en-us"
title = "jneo8.github.io"
disqusShortname = "jneo8"
theme = "sk3"
googleAnalytics = "UA-171057898-1"
staticDir = ["static"]

[Params]
mainSections = "posts flink kubernetes reading"
subtitle = "There is no spoon"
startdate = "2019-01-01"
listlastmod = true
pagewidth = "1200px"
paginate = 27
favicon = "/img/pikachu-icon.jpg"

# CSS
custom_css = ["/css/img.css"]
# JS
custom_js = ["/js/latex.js"]


# Twitter
opengraph = true
twittercards = true
title = "jneo8.github.io"
descrption = "There is no spoon"
pageinfobox = true

[Params.color]
bg     = "#FCFCFC"
border = "#FF9797"
link   = "#5B5B5B"
text   = "#272727"


[Params.card]
date = true
summary = true
width = "25%"

[Params.sociallink]
twitter = "lin_jneo8"
github = "jneo8"
linkedin = "james-lin-735548115"

[Params.socialshare]
twitter = true
facebook = true
linkedin = true
telegram = true

[markup]
  [markup.tableOfcontents]
  endLevel = 6
  startLevel = 2

[menu]
[[menu.main]]
name = "Tags"
url = "/tags"
[[menu.main]]
name = "WIP"
url = "/wip"
