baseURL = "https://jneo8.github.io"
languageCode = "en-us"
title = "jneo8.github.io"
theme = "coder"
staticDir = ["static"]
paginate = 27

# Disqus
disqusShortname = "jneo8"
# GA
googleAnalytics = "UA-171057898-1"

[params]
author = "jneo8"
info = "Backend/Data Engineer"
description = "jneo8's blog"
keywords = "blog,backend,developer,flink,kubernetes"
avatarURL = "/img/pikachu-icon.jpg"
favicon_32 = "/img/pikachu-icon.jpg"
since = "2020"
math = true
katex = true
colorScheme = "auto"
customCSS = ["/css/img.css"]

[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/jneo8/"

[[params.social]]
name = "Twitter"
icon = "fa fa-twitter fa-2x"
weight = 2
url = "https://twitter.com/lin_jneo8/"

[menu]
[[menu.main]]
name = "Tags"
url = "/tags"
weight = 100
[[menu.main]]
name = "WIP"
url = "/wip"
weight = 101
